# tools/fireant_mappings.py
import pandas as pd

# ---------------------------------------------------------------------------
# FIREANT EXACT TAXONOMY (As seen in the screenshots)
# ---------------------------------------------------------------------------
FIREANT_KQKD = [
    {"item_id": "kqkd_1", "item": "1. Tổng doanh thu hoạt động kinh doanh", "levels": 0, "kbsv_id": "2206"},
    {"item_id": "kqkd_2", "item": "2. Các khoản giảm trừ doanh thu", "levels": 0, "kbsv_id": "2218"},
    {"item_id": "kqkd_3", "item": "3. Doanh thu thuần (1)-(2)", "levels": 0, "kbsv_id": "2216"},
    {"item_id": "kqkd_4", "item": "4. Giá vốn hàng bán", "levels": 0, "kbsv_id": "2207"},
    {"item_id": "kqkd_5", "item": "5. Lợi nhuận gộp (3)-(4)", "levels": 0, "kbsv_id": "2217"},
    {"item_id": "kqkd_6", "item": "6. Doanh thu hoạt động tài chính", "levels": 0, "kbsv_id": "2221"},
    {"item_id": "kqkd_7", "item": "7. Chi phí tài chính", "levels": 0, "kbsv_id": "2222"},
    {"item_id": "kqkd_7_1", "item": "-Trong đó: Chi phí lãi vay", "levels": 1, "kbsv_id": "2223"},
    {"item_id": "kqkd_8", "item": "8. Phần lợi nhuận hoặc lỗ trong công ty liên kết liên doanh", "levels": 0, "kbsv_id": "5321"},
    {"item_id": "kqkd_9", "item": "9. Chi phí bán hàng", "levels": 0, "kbsv_id": "2227"},
    {"item_id": "kqkd_10", "item": "10. Chi phí quản lý doanh nghiệp", "levels": 0, "kbsv_id": "2224"},
    {"item_id": "kqkd_11", "item": "11. Lợi nhuận thuần từ hoạt động kinh doanh (5)+(6)-(7)+(8)-(9)-(10)", "levels": 0, "kbsv_id": "2208"},
    {"item_id": "kqkd_12", "item": "12. Thu nhập khác", "levels": 0, "kbsv_id": "2225"},
    {"item_id": "kqkd_13", "item": "13. Chi phí khác", "levels": 0, "kbsv_id": "2226"},
    {"item_id": "kqkd_14", "item": "14. Lợi nhuận khác (12)-(13)", "levels": 0, "kbsv_id": "2209"},
    {"item_id": "kqkd_15", "item": "15. Tổng lợi nhuận kế toán trước thuế (11)+(14)", "levels": 0, "kbsv_id": "2211"},
    {"item_id": "kqkd_16", "item": "16. Chi phí thuế TNDN hiện hành", "levels": 0, "kbsv_id": "2219"},
    {"item_id": "kqkd_17", "item": "17. Chi phí thuế TNDN hoãn lại", "levels": 0, "kbsv_id": "2220"},
    {"item_id": "kqkd_18", "item": "18. Chi phí thuế TNDN (16)+(17)", "levels": 0, "kbsv_id": "CALC_TAX"}, # We calculate this if KBSV lacks it
    {"item_id": "kqkd_19", "item": "19. Lợi nhuận sau thuế thu nhập doanh nghiệp (15)-(18)", "levels": 0, "kbsv_id": "2212"},
    {"item_id": "kqkd_20", "item": "20. Lợi nhuận sau thuế của cổ đông không kiểm soát", "levels": 0, "kbsv_id": "2213"},
    {"item_id": "kqkd_21", "item": "21. Lợi nhuận sau thuế của cổ đông của công ty mẹ (19)-(20)", "levels": 0, "kbsv_id": "2214"}
]

FIREANT_LCTT_TRUC_TIEP = [
    {"item_id": "lctttt_1", "item": "I. Lưu chuyển tiền từ hoạt động kinh doanh", "levels": 0, "kbsv_id": None},
    {"item_id": "lctttt_2", "item": "1. Tiền thu từ bán hàng, cung cấp dịch vụ và doanh thu khác", "levels": 1, "kbsv_id": "2270"},
    {"item_id": "lctttt_3", "item": "2. Tiền chi trả cho người cung cấp hàng hóa và dịch vụ", "levels": 1, "kbsv_id": "2271"},
    {"item_id": "lctttt_4", "item": "3. Tiền chi trả cho người lao động", "levels": 1, "kbsv_id": "2272"},
    {"item_id": "lctttt_5", "item": "4. Tiền chi trả lãi vay", "levels": 1, "kbsv_id": "2273"},
    {"item_id": "lctttt_6", "item": "5. Tiền chi nộp thuế thu nhập doanh nghiệp", "levels": 1, "kbsv_id": "2274"},
    {"item_id": "lctttt_7", "item": "6. Tiền thu khác từ hoạt động kinh doanh", "levels": 1, "kbsv_id": "2275"},
    {"item_id": "lctttt_8", "item": "7. Tiền chi khác cho hoạt động kinh doanh", "levels": 1, "kbsv_id": "2276"},
    {"item_id": "lctttt_9", "item": "Lưu chuyển tiền thuần từ hoạt động kinh doanh", "levels": 1, "kbsv_id": "2277"},
    {"item_id": "lctttt_10", "item": "II. Lưu chuyển tiền từ hoạt động đầu tư", "levels": 0, "kbsv_id": "2230"},
    {"item_id": "lctttt_11", "item": "Lưu chuyển tiền thuần từ hoạt động đầu tư", "levels": 1, "kbsv_id": "2235"},
    {"item_id": "lctttt_12", "item": "III. Lưu chuyển tiền từ hoạt động tài chính", "levels": 0, "kbsv_id": "2231"},
    {"item_id": "lctttt_13", "item": "Lưu chuyển tiền thuần từ hoạt động tài chính", "levels": 1, "kbsv_id": "2236"},
    {"item_id": "lctttt_14", "item": "Lưu chuyển tiền thuần trong kỳ", "levels": 0, "kbsv_id": "2238"},
    {"item_id": "lctttt_15", "item": "Tiền và tương đương tiền đầu kỳ", "levels": 0, "kbsv_id": "2239"},
    {"item_id": "lctttt_16", "item": "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ", "levels": 0, "kbsv_id": "2237"},
    {"item_id": "lctttt_17", "item": "Tiền và tương đương tiền cuối kỳ", "levels": 0, "kbsv_id": "2240"}
]

FIREANT_LCTT_GIAN_TIEP = [
    {"item_id": "lcttgt_1", "item": "I. Lưu chuyển tiền từ hoạt động kinh doanh", "levels": 0, "kbsv_id": "2228"},
    {"item_id": "lcttgt_2", "item": "1. Lợi nhuận trước thuế", "levels": 1, "kbsv_id": "2232"},
    {"item_id": "lcttgt_3", "item": "2. Điều chỉnh cho các khoản", "levels": 1, "kbsv_id": "2229"},
    {"item_id": "lcttgt_4", "item": "- Khấu hao TSCĐ", "levels": 2, "kbsv_id": "2242"},
    {"item_id": "lcttgt_5", "item": "- Các khoản dự phòng", "levels": 2, "kbsv_id": "2243"},
    {"item_id": "lcttgt_6", "item": "- Lợi nhuận thuần từ đầu tư vào công ty liên kết", "levels": 2, "kbsv_id": None},
    {"item_id": "lcttgt_7", "item": "- Xóa sổ tài sản cố định (thuần)", "levels": 2, "kbsv_id": None},
    {"item_id": "lcttgt_8", "item": "- Lãi, lỗ chênh lệch tỷ giá hối đoái chưa thực hiện", "levels": 2, "kbsv_id": "2244"},
    {"item_id": "lcttgt_9", "item": "- Lãi, lỗ từ thanh lý TSCĐ", "levels": 2, "kbsv_id": "5271"},
    {"item_id": "lcttgt_10", "item": "- Lãi, lỗ từ hoạt động đầu tư", "levels": 2, "kbsv_id": "2245"},
    {"item_id": "lcttgt_11", "item": "- Lãi tiền gửi", "levels": 2, "kbsv_id": None},
    {"item_id": "lcttgt_12", "item": "- Thu nhập lãi", "levels": 2, "kbsv_id": "5272"},
    {"item_id": "lcttgt_13", "item": "- Chi phí lãi vay", "levels": 2, "kbsv_id": "2241"},
    {"item_id": "lcttgt_14", "item": "- Các khoản chi trực tiếp từ lợi nhuận", "levels": 2, "kbsv_id": None},
    {"item_id": "lcttgt_15", "item": "3. Lợi nhuận từ hoạt động kinh doanh trước thay đổi vốn lưu động", "levels": 1, "kbsv_id": "2233"},
    {"item_id": "lcttgt_16", "item": "- Tăng, giảm các khoản phải thu", "levels": 2, "kbsv_id": "2246"},
    {"item_id": "lcttgt_17", "item": "- Tăng, giảm hàng tồn kho", "levels": 2, "kbsv_id": "2247"},
    {"item_id": "lcttgt_18", "item": "- Tăng, giảm các khoản phải trả (Không kể lãi vay phải trả, thuế thu nhập doanh nghiệp phải nộp)", "levels": 2, "kbsv_id": "2248"},
    {"item_id": "lcttgt_19", "item": "- Tăng giảm chi phí trả trước", "levels": 2, "kbsv_id": "2249"},
    {"item_id": "lcttgt_20", "item": "- Tăng giảm chứng khoán kinh doanh", "levels": 2, "kbsv_id": "5317"},
    {"item_id": "lcttgt_21", "item": "- Tiền lãi vay đã trả", "levels": 2, "kbsv_id": "2250"},
    {"item_id": "lcttgt_22", "item": "- Thuế thu nhập doanh nghiệp đã nộp", "levels": 2, "kbsv_id": "2251"},
    {"item_id": "lcttgt_23", "item": "- Tiền thu khác từ hoạt động kinh doanh", "levels": 2, "kbsv_id": "2252"},
    {"item_id": "lcttgt_24", "item": "- Tiền chi khác từ hoạt động kinh doanh", "levels": 2, "kbsv_id": "2253"},
    {"item_id": "lcttgt_25", "item": "Lưu chuyển tiền thuần từ hoạt động kinh doanh", "levels": 1, "kbsv_id": "2234"},
    {"item_id": "lcttgt_26", "item": "II. Lưu chuyển tiền từ hoạt động đầu tư", "levels": 0, "kbsv_id": "2230"},
    {"item_id": "lcttgt_27", "item": "1. Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác", "levels": 1, "kbsv_id": "2254"},
    {"item_id": "lcttgt_28", "item": "2. Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác", "levels": 1, "kbsv_id": "2255"},
    {"item_id": "lcttgt_29", "item": "3. Tiền chi cho vay, mua các công cụ nợ của đơn vị khác", "levels": 1, "kbsv_id": "2256"},
    {"item_id": "lcttgt_30", "item": "4. Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác", "levels": 1, "kbsv_id": "2257"},
    {"item_id": "lcttgt_31", "item": "5. Đầu tư góp vốn vào công ty liên doanh liên kết", "levels": 1, "kbsv_id": None},
    {"item_id": "lcttgt_32", "item": "6. Chi đầu tư ngắn hạn", "levels": 1, "kbsv_id": None},
    {"item_id": "lcttgt_33", "item": "7. Tiền chi đầu tư góp vốn vào đơn vị khác", "levels": 1, "kbsv_id": "2258"},
    {"item_id": "lcttgt_34", "item": "8. Tiền thu hồi đầu tư góp vốn vào đơn vị khác", "levels": 1, "kbsv_id": "2259"},
    {"item_id": "lcttgt_35", "item": "9. Lãi tiền gửi đã thu", "levels": 1, "kbsv_id": None},
    {"item_id": "lcttgt_36", "item": "10. Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia", "levels": 1, "kbsv_id": "2260"},
    {"item_id": "lcttgt_37", "item": "11. Tiền chi mua lại phần vốn góp của các cổ đông thiểu số", "levels": 1, "kbsv_id": "4068"},
    {"item_id": "lcttgt_38", "item": "Lưu chuyển tiền thuần từ hoạt động đầu tư", "levels": 1, "kbsv_id": "2235"},
    {"item_id": "lcttgt_39", "item": "III. Lưu chuyển tiền từ hoạt động tài chính", "levels": 0, "kbsv_id": "2231"},
    {"item_id": "lcttgt_40", "item": "1. Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu", "levels": 1, "kbsv_id": "2261"},
    {"item_id": "lcttgt_41", "item": "2. Tiền chi trả vốn góp cho các chủ sở hữu, mua lại cổ phiếu của doanh nghiệp đã phát hành", "levels": 1, "kbsv_id": "2262"},
    {"item_id": "lcttgt_42", "item": "3. Tiền vay ngắn hạn, dài hạn nhận được", "levels": 1, "kbsv_id": "2263"},
    {"item_id": "lcttgt_43", "item": "4. Tiền chi trả nợ gốc vay", "levels": 1, "kbsv_id": "2264"},
    {"item_id": "lcttgt_44", "item": "5. Tiền chi trả nợ thuê tài chính", "levels": 1, "kbsv_id": "2265"},
    {"item_id": "lcttgt_45", "item": "6. Tiền chi khác từ hoạt động tài chính", "levels": 1, "kbsv_id": "5279"},
    {"item_id": "lcttgt_46", "item": "7. Tiền chi trả từ cổ phần hóa", "levels": 1, "kbsv_id": None},
    {"item_id": "lcttgt_47", "item": "8. Cổ tức, lợi nhuận đã trả cho chủ sở hữu", "levels": 1, "kbsv_id": "2266"},
    {"item_id": "lcttgt_48", "item": "9. Vốn góp của các cổ đông thiểu số vào các công ty con", "levels": 1, "kbsv_id": None},
    {"item_id": "lcttgt_49", "item": "10. Chi tiêu quỹ phúc lợi xã hội", "levels": 1, "kbsv_id": None},
    {"item_id": "lcttgt_50", "item": "Lưu chuyển tiền thuần từ hoạt động tài chính", "levels": 1, "kbsv_id": "2236"},
    {"item_id": "lcttgt_51", "item": "Lưu chuyển tiền thuần trong kỳ", "levels": 0, "kbsv_id": "2238"},
    {"item_id": "lcttgt_52", "item": "Tiền và tương đương tiền đầu kỳ", "levels": 0, "kbsv_id": "2239"},
    {"item_id": "lcttgt_53", "item": "Ảnh hưởng của thay đổi tỷ giá hối đoái quy đổi ngoại tệ", "levels": 0, "kbsv_id": "2237"},
    {"item_id": "lcttgt_54", "item": "Tiền và tương đương tiền cuối kỳ", "levels": 0, "kbsv_id": "2240"}
]

FIREANT_CDKT = [
    {"item_id": "cdkt_1", "item": "TÀI SẢN", "levels": 0, "kbsv_id": "2995"},
    {"item_id": "cdkt_2", "item": "A. Tài sản lưu động và đầu tư ngắn hạn", "levels": 1, "kbsv_id": "3000"},
    {"item_id": "cdkt_3", "item": "I. Tiền và các khoản tương đương tiền", "levels": 2, "kbsv_id": "3003"},
    {"item_id": "cdkt_4", "item": "1. Tiền", "levels": 3, "kbsv_id": "3018"},
    {"item_id": "cdkt_5", "item": "2. Các khoản tương đương tiền", "levels": 3, "kbsv_id": "3019"},
    {"item_id": "cdkt_6", "item": "II. Các khoản đầu tư tài chính ngắn hạn", "levels": 2, "kbsv_id": "3004"},
    {"item_id": "cdkt_7", "item": "1. Chứng khoán kinh doanh", "levels": 3, "kbsv_id": "3020"},
    {"item_id": "cdkt_8", "item": "2. Dự phòng giảm giá chứng khoán kinh doanh (*)", "levels": 3, "kbsv_id": "3021"},
    {"item_id": "cdkt_9", "item": "3. Đầu tư nắm giữ đến ngày đáo hạn", "levels": 3, "kbsv_id": "5297"},
    {"item_id": "cdkt_10", "item": "III. Các khoản phải thu ngắn hạn", "levels": 2, "kbsv_id": "3005"},
    {"item_id": "cdkt_11", "item": "1. Phải thu ngắn hạn của khách hàng", "levels": 3, "kbsv_id": "3022"},
    {"item_id": "cdkt_12", "item": "2. Trả trước cho người bán ngắn hạn", "levels": 3, "kbsv_id": "3023"},
    {"item_id": "cdkt_13", "item": "3. Phải thu nội bộ ngắn hạn", "levels": 3, "kbsv_id": "3024"},
    {"item_id": "cdkt_14", "item": "4. Phải thu theo tiến độ kế hoạch hợp đồng xây dựng", "levels": 3, "kbsv_id": "3025"},
    {"item_id": "cdkt_15", "item": "5. Phải thu về cho vay ngắn hạn", "levels": 3, "kbsv_id": "5300"},
    {"item_id": "cdkt_16", "item": "6. Phải thu ngắn hạn khác", "levels": 3, "kbsv_id": "3026"},
    {"item_id": "cdkt_17", "item": "7. Dự phòng phải thu ngắn hạn khó đòi (*)", "levels": 3, "kbsv_id": "3079"},
    {"item_id": "cdkt_18", "item": "8. Tài sản thiếu chờ xử lý", "levels": 3, "kbsv_id": "5299"},
    {"item_id": "cdkt_19", "item": "IV. Tổng hàng tồn kho", "levels": 2, "kbsv_id": "3006"},
    {"item_id": "cdkt_20", "item": "1. Hàng tồn kho", "levels": 3, "kbsv_id": "3027"},
    {"item_id": "cdkt_21", "item": "2. Dự phòng giảm giá hàng tồn kho (*)", "levels": 3, "kbsv_id": "3080"},
    {"item_id": "cdkt_22", "item": "V. Tài sản ngắn hạn khác", "levels": 2, "kbsv_id": "3007"},
    {"item_id": "cdkt_23", "item": "1. Chi phí trả trước ngắn hạn", "levels": 3, "kbsv_id": "3028"},
    {"item_id": "cdkt_24", "item": "2. Thuế GTGT được khấu trừ", "levels": 3, "kbsv_id": "3029"},
    {"item_id": "cdkt_25", "item": "3. Thuế và các khoản khác phải thu của nhà nước", "levels": 3, "kbsv_id": "3030"},
    {"item_id": "cdkt_26", "item": "4. Giao dịch mua bán lại trái phiếu chính phủ", "levels": 3, "kbsv_id": "5270"},
    {"item_id": "cdkt_27", "item": "5. Tài sản ngắn hạn khác", "levels": 3, "kbsv_id": "3031"},
    {"item_id": "cdkt_28", "item": "B. Tài sản cố định và đầu tư dài hạn", "levels": 1, "kbsv_id": "3001"},
    {"item_id": "cdkt_29", "item": "I. Các khoản phải thu dài hạn", "levels": 2, "kbsv_id": "3008"},
    {"item_id": "cdkt_30", "item": "1. Phải thu dài hạn của khách hàng", "levels": 3, "kbsv_id": "3032"},
    {"item_id": "cdkt_31", "item": "2. Trả trước cho người bán dài hạn", "levels": 3, "kbsv_id": "5301"},
    {"item_id": "cdkt_32", "item": "3. Vốn kinh doanh ở các đơn vị trực thuộc", "levels": 3, "kbsv_id": "3033"},
    {"item_id": "cdkt_33", "item": "4. Phải thu nội bộ dài hạn", "levels": 3, "kbsv_id": "3034"},
    {"item_id": "cdkt_34", "item": "5. Phải thu về cho vay dài hạn", "levels": 3, "kbsv_id": "5302"},
    {"item_id": "cdkt_35", "item": "6. Phải thu dài hạn khác", "levels": 3, "kbsv_id": "3081"},
    {"item_id": "cdkt_36", "item": "7. Dự phòng phải thu dài hạn khó đòi (*)", "levels": 3, "kbsv_id": "3082"},
    {"item_id": "cdkt_37", "item": "II. Tài sản cố định", "levels": 2, "kbsv_id": "3009"},
    {"item_id": "cdkt_38", "item": "1. Tài sản cố định hữu hình", "levels": 3, "kbsv_id": "3035"},
    {"item_id": "cdkt_39", "item": "- Nguyên giá", "levels": 4, "kbsv_id": "3083"},
    {"item_id": "cdkt_40", "item": "- Giá trị hao mòn lũy kế (*)", "levels": 4, "kbsv_id": "3084"},
    {"item_id": "cdkt_41", "item": "2. Tài sản cố định thuê tài chính", "levels": 3, "kbsv_id": "3036"},
    {"item_id": "cdkt_42", "item": "- Nguyên giá", "levels": 4, "kbsv_id": "3085"},
    {"item_id": "cdkt_43", "item": "- Giá trị hao mòn lũy kế (*)", "levels": 4, "kbsv_id": "3086"},
    {"item_id": "cdkt_44", "item": "3. Tài sản cố định vô hình", "levels": 3, "kbsv_id": "3037"},
    {"item_id": "cdkt_45", "item": "- Nguyên giá", "levels": 4, "kbsv_id": "3087"},
    {"item_id": "cdkt_46", "item": "- Giá trị hao mòn lũy kế (*)", "levels": 4, "kbsv_id": "3088"},
    {"item_id": "cdkt_47", "item": "III. Bất động sản đầu tư", "levels": 2, "kbsv_id": "3010"},
    {"item_id": "cdkt_48", "item": "- Nguyên giá", "levels": 3, "kbsv_id": "3039"},
    {"item_id": "cdkt_49", "item": "- Giá trị hao mòn lũy kế (*)", "levels": 3, "kbsv_id": "3040"},
    {"item_id": "cdkt_50", "item": "IV. Tài sản dở dang dài hạn", "levels": 2, "kbsv_id": "5298"},
    {"item_id": "cdkt_51", "item": "1. Chi phí sản xuất, kinh doanh dở dang dài hạn", "levels": 3, "kbsv_id": "5303"},
    {"item_id": "cdkt_52", "item": "2. Chi phí xây dựng cơ bản dở dang", "levels": 3, "kbsv_id": "3038"},
    {"item_id": "cdkt_53", "item": "V. Các khoản đầu tư tài chính dài hạn", "levels": 2, "kbsv_id": "3011"},
    {"item_id": "cdkt_54", "item": "1. Đầu tư vào công ty con", "levels": 3, "kbsv_id": "3041"},
    {"item_id": "cdkt_55", "item": "2. Đầu tư vào công ty liên kết, liên doanh", "levels": 3, "kbsv_id": "3042"},
    {"item_id": "cdkt_56", "item": "3. Đầu tư góp vốn vào đơn vị khác", "levels": 3, "kbsv_id": "5304"},
    {"item_id": "cdkt_57", "item": "4. Dự phòng đầu tư tài chính dài hạn (*)", "levels": 3, "kbsv_id": "3044"},
    {"item_id": "cdkt_58", "item": "5. Đầu tư nắm giữ đến ngày đáo hạn", "levels": 3, "kbsv_id": "5312"},
    {"item_id": "cdkt_59", "item": "6. Đầu tư dài hạn khác", "levels": 3, "kbsv_id": "3043"},
    {"item_id": "cdkt_60", "item": "VI. Tổng tài sản dài hạn khác", "levels": 2, "kbsv_id": "3013"},
    {"item_id": "cdkt_61", "item": "1. Chi phí trả trước dài hạn", "levels": 3, "kbsv_id": "3045"},
    {"item_id": "cdkt_62", "item": "2. Tài sản thuế thu nhập hoãn lại", "levels": 3, "kbsv_id": "3046"},
    {"item_id": "cdkt_63", "item": "3. Thiết bị, vật tư, phụ tùng thay thế dài hạn", "levels": 3, "kbsv_id": "5305"},
    {"item_id": "cdkt_64", "item": "4. Tài sản dài hạn khác", "levels": 3, "kbsv_id": "3047"},
    {"item_id": "cdkt_65", "item": "VII. Lợi thế thương mại", "levels": 2, "kbsv_id": "3012"},
    {"item_id": "cdkt_66", "item": "TỔNG CỘNG TÀI SẢN", "levels": 0, "kbsv_id": "2996"},
    
    {"item_id": "cdkt_67", "item": "NGUỒN VỐN", "levels": 0, "kbsv_id": "2994"},
    {"item_id": "cdkt_68", "item": "A. Nợ phải trả", "levels": 1, "kbsv_id": "2997"},
    {"item_id": "cdkt_69", "item": "I. Nợ ngắn hạn", "levels": 2, "kbsv_id": "3014"},
    {"item_id": "cdkt_70", "item": "1. Phải trả người bán ngắn hạn", "levels": 3, "kbsv_id": "3048"},
    {"item_id": "cdkt_71", "item": "2. Người mua trả tiền trước ngắn hạn", "levels": 3, "kbsv_id": "3049"},
    {"item_id": "cdkt_72", "item": "3. Thuế và các khoản phải nộp Nhà nước", "levels": 3, "kbsv_id": "3050"},
    {"item_id": "cdkt_73", "item": "4. Phải trả người lao động", "levels": 3, "kbsv_id": "3051"},
    {"item_id": "cdkt_74", "item": "5. Chi phí phải trả ngắn hạn", "levels": 3, "kbsv_id": "3052"},
    {"item_id": "cdkt_75", "item": "6. Phải trả nội bộ ngắn hạn", "levels": 3, "kbsv_id": "3053"},
    {"item_id": "cdkt_76", "item": "7. Phải trả theo tiến độ kế hoạch hợp đồng xây dựng", "levels": 3, "kbsv_id": "3054"},
    {"item_id": "cdkt_77", "item": "8. Doanh thu chưa thực hiện ngắn hạn", "levels": 3, "kbsv_id": "4804"},
    {"item_id": "cdkt_78", "item": "9. Phải trả ngắn hạn khác", "levels": 3, "kbsv_id": "3055"},
    {"item_id": "cdkt_79", "item": "10. Vay và nợ thuê tài chính ngắn hạn", "levels": 3, "kbsv_id": "3077"},
    {"item_id": "cdkt_80", "item": "11. Dự phòng phải trả ngắn hạn", "levels": 3, "kbsv_id": "3056"},
    {"item_id": "cdkt_81", "item": "12. Quỹ khen thưởng, phúc lợi", "levels": 3, "kbsv_id": "3074"},
    {"item_id": "cdkt_82", "item": "13. Quỹ bình ổn giá", "levels": 3, "kbsv_id": "5306"},
    {"item_id": "cdkt_83", "item": "14. Giao dịch mua bán lại trái phiếu Chính phủ", "levels": 3, "kbsv_id": "5269"},
    {"item_id": "cdkt_84", "item": "II. Nợ dài hạn", "levels": 2, "kbsv_id": "3017"},
    {"item_id": "cdkt_85", "item": "1. Phải trả người bán dài hạn", "levels": 3, "kbsv_id": "3057"},
    {"item_id": "cdkt_86", "item": "2. Người mua trả tiền trước dài hạn", "levels": 3, "kbsv_id": "5307"},
    {"item_id": "cdkt_87", "item": "3. Chi phí phải trả dài hạn", "levels": 3, "kbsv_id": "5308"},
    {"item_id": "cdkt_88", "item": "4. Phải trả nội bộ về vốn kinh doanh", "levels": 3, "kbsv_id": "5309"},
    {"item_id": "cdkt_89", "item": "5. Phải trả nội bộ dài hạn", "levels": 3, "kbsv_id": "3058"},
    {"item_id": "cdkt_90", "item": "6. Doanh thu chưa thực hiện dài hạn", "levels": 3, "kbsv_id": "4066"},
    {"item_id": "cdkt_91", "item": "7. Phải trả dài hạn khác", "levels": 3, "kbsv_id": "3059"},
    {"item_id": "cdkt_92", "item": "8. Vay và nợ thuê tài chính dài hạn", "levels": 3, "kbsv_id": "3078"},
    {"item_id": "cdkt_93", "item": "9. Trái phiếu chuyển đổi", "levels": 3, "kbsv_id": "5310"},
    {"item_id": "cdkt_94", "item": "10. Cổ phiếu ưu đãi (Nợ)", "levels": 3, "kbsv_id": "5319"},
    {"item_id": "cdkt_95", "item": "11. Thuế thu nhập hoãn lại phải trả", "levels": 3, "kbsv_id": "3060"},
    {"item_id": "cdkt_96", "item": "12. Dự phòng phải trả dài hạn", "levels": 3, "kbsv_id": "3062"},
    {"item_id": "cdkt_97", "item": "13. Quỹ phát triển khoa học và công nghệ", "levels": 3, "kbsv_id": "4067"},
    {"item_id": "cdkt_98", "item": "14. Dự phòng trợ cấp mất việc làm", "levels": 3, "kbsv_id": "3061"},
    {"item_id": "cdkt_99", "item": "B. Nguồn vốn chủ sở hữu", "levels": 1, "kbsv_id": "2998"},
    {"item_id": "cdkt_100", "item": "I. Vốn chủ sở hữu", "levels": 2, "kbsv_id": "3015"},
    {"item_id": "cdkt_101", "item": "1. Vốn góp của chủ sở hữu", "levels": 3, "kbsv_id": "3063"},
    {"item_id": "cdkt_102", "item": "- Cổ phiếu phổ thông có quyền biểu quyết", "levels": 4, "kbsv_id": "5313"},
    {"item_id": "cdkt_103", "item": "- Cổ phiếu ưu đãi", "levels": 4, "kbsv_id": "5318"},
    {"item_id": "cdkt_104", "item": "2. Thặng dư vốn cổ phần", "levels": 3, "kbsv_id": "3064"},
    {"item_id": "cdkt_105", "item": "3. Quyền chọn chuyển đổi trái phiếu", "levels": 3, "kbsv_id": "5311"},
    {"item_id": "cdkt_106", "item": "4. Vốn khác của chủ sở hữu", "levels": 3, "kbsv_id": "3065"},
    {"item_id": "cdkt_107", "item": "5. Cổ phiếu quỹ (*)", "levels": 3, "kbsv_id": "3066"},
    {"item_id": "cdkt_108", "item": "6. Chênh lệch đánh giá lại tài sản", "levels": 3, "kbsv_id": "3067"},
    {"item_id": "cdkt_109", "item": "7. Chênh lệch tỷ giá hối đoái", "levels": 3, "kbsv_id": "3068"},
    {"item_id": "cdkt_110", "item": "8. Quỹ đầu tư phát triển", "levels": 3, "kbsv_id": "3069"},
    {"item_id": "cdkt_111", "item": "9. Quỹ hỗ trợ sắp xếp doanh nghiệp", "levels": 3, "kbsv_id": "4073"},
    {"item_id": "cdkt_112", "item": "10. Quỹ khác thuộc vốn chủ sở hữu", "levels": 3, "kbsv_id": "3071"},
    {"item_id": "cdkt_113", "item": "11. Lợi nhuận sau thuế chưa phân phối", "levels": 3, "kbsv_id": "3072"},
    {"item_id": "cdkt_114", "item": "- LNST chưa phân phối lũy kế đến cuối kỳ trước", "levels": 4, "kbsv_id": "5314"},
    {"item_id": "cdkt_115", "item": "- LNST chưa phân phối kỳ này", "levels": 4, "kbsv_id": "5315"},
    {"item_id": "cdkt_116", "item": "12. Nguồn vốn đầu tư XDCB", "levels": 3, "kbsv_id": "3073"},
    {"item_id": "cdkt_117", "item": "13. Lợi ích cổ đông không kiểm soát", "levels": 3, "kbsv_id": "5320"},
    {"item_id": "cdkt_118", "item": "14. Quỹ dự phòng tài chính", "levels": 3, "kbsv_id": "3070"},
    {"item_id": "cdkt_119", "item": "II. Nguồn kinh phí và quỹ khác", "levels": 2, "kbsv_id": "3016"},
    {"item_id": "cdkt_120", "item": "TỔNG CỘNG NGUỒN VỐN", "levels": 0, "kbsv_id": "2999"}
]
